name: bench

on: [push, pull_request]

jobs:
  bench:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12'
        architecture: x64
    - name: Cache m2 repository
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Install dependencies
      run: lein with-profile bench deps
    - name: Benchmarking
      run: make bench
